### ISSUE TITLE
Usable in Objective-C?

### ISSUE THREAD

**Issue by paulrolfe** [delannoyk/GIFRefreshControl#1]
I tried using this as a pod in my objective-c project. It looks like the `animatedImage` property is not exposed in the header... I'm just double checking that's the case and that this pod is not fully compatible with objc -- right?

**Comment by delannoyk** [comment]
It should be with a little work on my end. I think the issue here is that `animatedImage` is a property that implements `AnimatedImage` protocol and this protocol is not marked `@objc`.

I'll check it later today and will let you know here :-)

**Comment by delannoyk** [comment]
Yep, the protocol is definitely the issue here. I'll correct this later today.

**Comment by delannoyk** [comment]
@paulrolfe Fixed by 274bbe92eac916eac885c99fd227dfab0cd402b3 (v1.1.1).

Based on my test, everything works as expected! Can you confirm it's OK for you? :)

**Comment by paulrolfe** [comment]
Thanks, I'll give it a try tonight.

**Comment by delannoyk** [comment]
Hi @paulrolfe

Did you get a chance to try it?

**Comment by paulrolfe** [comment]
I did! It works like a charm. Thank you.

Paul Rolfe
paul.a.rolfe@gmail.com
Red Ostrich LLC || http://paulrolfe.com
