### ISSUE TITLE
Xcode 7 after convert to swift 2 Syntax build error

### ISSUE THREAD

**Issue by ajinkyashelar** [delannoyk/GIFRefreshControl#2]
Hi,

I converted the GIFRefreshControl.swift to Swift 2.0 syntax using the Xcode 7 tool. But it is still giving me a build error at one of the line, please let me know if you can help me out as I am not an expert in Swift.

Line 144 : private lazy var imageView = GIFAnimatedImageView()

Build Error : 
Cannot convert value of type 'UIImageView' to specified type 'GIFAnimatedImageView'

**Comment by delannoyk** [comment]
Hi @ajinkyashelar,
I'll try provide a swift 2.0 implementation by the end of the day (CEST).

Cheers,
Kevin

**Comment by ajinkyashelar** [comment]
Hi @delannoyk,

I was able to fix the error by removing the keyword lazy from line. I am not sure if that will create any other trouble. 

Before
Line 144 : private lazy var imageView = GIFAnimatedImageView()
After
Line 144 : private var imageView = GIFAnimatedImageView()

Cheers,
Ajinkya

**Comment by delannoyk** [comment]
Fixed in 1.2. 242ff004d7ae215c00e45f4eb4bce118e5a1dfd4

**Comment by delannoyk** [comment]
The `lazy` keyword didn't serve any purpose since it's used in `init`.

**Comment by ajinkyashelar** [comment]
Thanks for the updates!

**Comment by Ged2323** [comment]
Great works in 2.1
